-- Active: 1657835453971@@localhost@3306@vscodedb

SELECT P.BRAND_ID, BRAND_NAME, BRAND_TYPE, ROUND(MAX(AVERAGEPRICE), 2) AS AVGPRICE
    FROM (SELECT B.BRAND_ID, BRAND_NAME, BRAND_TYPE, AVG(PROD_PRICE) AS AVERAGEPRICE
    FROM LGBRAND AS B JOIN LGPRODUCT AS P ON B.BRAND_ID = P.BRAND_ID
    GROUP BY BRAND_ID) P
    GROUP BY BRAND_ID
    ORDER BY AVERAGEPRICE DESC
    LIMIT 1;
