-- Active: 1657835453971@@localhost@3306@vscodedb

SELECT MAX(AVGPRICE) AS 'LARGEST AVERAGE'
    FROM (SELECT BRAND_ID, ROUND(AVG(PROD_PRICE), 2) AS AVGPRICE
    FROM LGPRODUCT AS P
    GROUP BY BRAND_ID) B;
