-- Active: 1657835453971@@localhost@3306@vscodedb

SELECT BRAND_NAME, COUNT(PROD_SKU) AS NumProducts
    FROM LGBRAND AS B JOIN LGPRODUCT AS P ON B.BRAND_ID = P.BRAND_ID
    GROUP BY BRAND_NAME 
    ORDER BY BRAND_NAME;