-- Active: 1657835453971@@localhost@3306@vscodedb

SELECT V.VEND_ID, VEND_NAME, BRAND_NAME, COUNT(P.PROD_SKU) AS NUMPRODUCTS
    FROM LGVENDOR AS V JOIN LGSUPPLIES AS S ON V.VEND_ID = S.VEND_ID JOIN LGPRODUCT AS P ON S.PROD_SKU = P.PROD_SKU JOIN LGBRAND AS B ON P.BRAND_ID = B.BRAND_ID
    GROUP BY VEND_NAME, BRAND_NAME
    ORDER BY VEND_NAME, BRAND_NAME;