-- Active: 1657835453971@@localhost@3306@vscodedb

SELECT C.CUST_CODE, CUST_FNAME, CUST_LNAME, SUM(INV_TOTAL) AS TOTALINVOICES
    FROM LGCUSTOMER AS C JOIN LGINVOICE AS I ON C.CUST_CODE = I.CUST_CODE
    GROUP BY CUST_CODE
    HAVING TOTALINVOICES >= 1500
    ORDER BY TOTALINVOICES DESC;