-- Active: 1657835453971@@localhost@3306@vscodedb

SELECT EMP_NUM, EMP_LNAME, EMP_FNAME, SUM(INV_TOTAL) AS TOTALINVOICES
    FROM LGEMPLOYEE AS E JOIN LGINVOICE AS I ON E.EMP_NUM = I.EMPLOYEE_ID
    GROUP BY EMP_NUM
    ORDER BY EMP_LNAME, EMP_FNAME;