-- Active: 1657835453971@@localhost@3306@vscodedb

SELECT B.BRAND_ID, SUM(PROD_QOH)
    FROM LGBRAND AS B JOIN LGPRODUCT AS P ON B.BRAND_ID = P.BRAND_ID
    GROUP BY BRAND_ID
    ORDER BY BRAND_ID DESC;